// Config to turn on and off different bugs

const bugConfig = {
  bug_articles_001: false,
  bug_articles_002: false,
  bug_charts_001: false,
  bug_charts_002: false,
  bug_charts_003: false,
  bug_validation_001: false,
  bug_validation_002: false,
  bug_validation_003: false,
  bug_validation_004: false,
  bug_validation_005: false,
  bug_validation_006: false,
  bug_validation_007: false,
  bug_validation_008: false,
  bug_quiz_001: false,
  bug_quiz_002: false,
  bug_quiz_003: false,
  bug_quiz_004: false,
  bug_sorting_001: false,
  bug_sorting_002: false,
  bug_sorting_003: false,
  bug_likes_001: false,
  bug_likes_002: false,
  bug_likes_003: false,
  bug_bookmarks_001: false,
  bug_bookmarks_002: false,
  bug_bookmarks_003: false,
  bug_survey_001: false,
  bug_survey_002: false,
  bug_survey_003: false,
  bug_survey_004: false,
  bug_game_ttt_001: false,
  bug_game_ttt_002: false,
  bug_game_ttt_003: false,
  bug_random_503: false,
  bug_random_404_get: false,
  bug_slower_responses_100ms: false,
  bug_slower_responses_500ms: false,
  bug_slower_responses_1000ms: false,
  bug_slower_responses_2500ms: false,
  bug_disable_module_comments: false,
  bug_disable_module_users: false,
  bug_disable_module_articles: false,
  bug_disable_module_auth: false,
};

module.exports = {
  bugConfig,
};
