// simple log levels
const LogLevels = {
  ERROR: 0,
  CONSOLE: 1,
  WARNING: 2,
  DEBUG: 4,
  TRACE: 5,
  INSANE: 10,
};

const ConfigKeys = {
  ADMIN_USER_EMAIL: "adminUserEmail",
  ADMIN_USER_PASS: "adminUserPass",
  BEARER_TOKEN: "bearerToken",
  BASIC_AUTH: "basicAuth",
  CHARACTERS: "characters",
  JWT_SECRET_KEY: "JWT_SECRET_KEY",
  TOKEN_EXPIRATION_MINUTES: "tokenExpirationInMinutes",
  SUPER_ADMIN_TOKEN_EXPIRATION_MINUTES: "superAdminTokenExpirationInMinutes",
  COOKIE_MAX_AGE: "cookieMaxAge",
  SUPER_ADMIN_COOKIE_MAX_AGE: "superAdminCookieMaxAge",
  KEEP_SIGNIN_COOKIE_MAX_AGE: "keepSignInCookieMaxAge",
  TOKEN_EXPIRES_IN: "tokenExpiresIn",
  SUPER_ADMIN_TOKEN_EXPIRES_IN: "superAdminTokenExpiresIn",
  KEEP_SIGNIN_TOKEN_EXPIRES_IN: "keepSignInTokenExpiresIn",
  AUTH_USER_DB: "authUserDb",
  GAMES_DB: "gamesDbPath",
  TRANSLATIONS_DB: "translationsDbPath",
  DB_PATH: "dbPath",
  DB_RESTORE_PATH: "dbRestorePath",
  DB2_RESTORE_PATH: "db2RestorePath",
  DB_BIG_RESTORE_PATH: "dbBigRestorePath",
  DB_TINY_RESTORE_PATH: "dbTinyRestorePath",
  DB_EMPTY_RESTORE_PATH: "dbEmptyRestorePath",
  QUIZ_QUESTIONS_PATH: "quizQuestionsPath",
  HANGMAN_DATA_PATH: "hangmanDataPath",
  DEFAULT_PORT: "defaultPort",
  SUPER_ADMIN_USER_EMAIL: "superAdminUserEmail",
  SUPER_ADMIN_USER_PASS: "superAdminUserPass",
  DATE_REGEXP: "dateRegexp",
  EMAIL_REGEXP: "emailRegexp",
  UPLOAD_SIZE_LIMIT_BYTES: "uploadSizeLimitBytes",
  CURRENT_LOG_LEVEL: "currentLogLevel",
  SLEEP_TIME_PER_ONE_GET_COMMENT: "sleepTimePerOneGetComment",
  SLEEP_TIME_PER_ONE_GET_COMMENT_MIN: "sleepTimePerOneGetCommentMin",
  SLEEP_TIME_PER_ONE_GET_COMMENT_MAX: "sleepTimePerOneGetCommentMax",
  PUBLIC_LOGS_ENABLED: "publicLogsEnabled",
  NUMBER_OF_TOP_LIKED_ARTICLES: "numberOfTopLikedArticles",
  USER_AVATAR_PATH: "userAvatarPath",
  ARTICLE_IMAGE_PATH: "articleImagePath",
  UPLOADS_PATH: "uploadsPath",
  LOGS_LIMIT: "logsLimit",
  NUMBER_OF_TOP_VISITED_ARTICLES: "numberOfTopVisitedArticles",
  MAX_RANDOM_VISITS_FOR_ARTICLES: "maxRandomVisitsForArticles",
  MIN_RANDOM_VISITS_FOR_ARTICLES: "minRandomVisitsForArticles",
  MAX_RANDOM_VISITS_FOR_COMMENTS: "maxRandomVisitsForComments",
  MIN_RANDOM_VISITS_FOR_COMMENTS: "minRandomVisitsForComments",
  MAX_RANDOM_VISITS_FOR_USERS: "maxRandomVisitsForUsers",
  MIN_RANDOM_VISITS_FOR_USERS: "minRandomVisitsForUsers",
  READ_ONLY: "readOnly",
  RANDOM_ERROR_RESPONSE_PROBABILITY: "randomErrorResponseProbability",
};

const BugConfigKeys = {
  BUG_CHARTS_001: "bug_charts_001",
  BUG_CHARTS_002: "bug_charts_002",
  BUG_CHARTS_003: "bug_charts_003",
  BUG_VALIDATION_001: "bug_validation_001",
  BUG_VALIDATION_002: "bug_validation_002",
  BUG_VALIDATION_003: "bug_validation_003",
  BUG_VALIDATION_004: "bug_validation_004",
  BUG_VALIDATION_005: "bug_validation_005",
  BUG_VALIDATION_006: "bug_validation_006",
  BUG_VALIDATION_007: "bug_validation_007",
  BUG_VALIDATION_008: "bug_validation_008",
  BUG_QUIZ_001: "bug_quiz_001",
  BUG_QUIZ_002: "bug_quiz_002",
  BUG_QUIZ_003: "bug_quiz_003",
  BUG_QUIZ_004: "bug_quiz_004",
  BUG_SORTING_001: "bug_sorting_001",
  BUG_SORTING_002: "bug_sorting_002",
  BUG_SORTING_003: "bug_sorting_003",
  BUG_LIKES_001: "bug_likes_001",
  BUG_LIKES_002: "bug_likes_002",
  BUG_LIKES_003: "bug_likes_003",
  BUG_BOOKMARKS_001: "bug_bookmarks_001",
  BUG_BOOKMARKS_002: "bug_bookmarks_002",
  BUG_BOOKMARKS_003: "bug_bookmarks_003",
  BUG_ARTICLES_001: "bug_articles_001",
  BUG_ARTICLES_002: "bug_articles_002",
  BUG_SURVEY_001: "bug_survey_001",
  BUG_SURVEY_002: "bug_survey_002",
  BUG_SURVEY_003: "bug_survey_003",
  BUG_SURVEY_004: "bug_survey_004",
  BUG_GAME_TTT_001: "bug_game_ttt_001",
  BUG_GAME_TTT_002: "bug_game_ttt_002",
  BUG_GAME_TTT_003: "bug_game_ttt_003",
  BUG_RANDOM_503: "bug_random_503",
  BUG_RANDOM_404_GET: "bug_random_404_get",
  BUG_SLOWER_RESPONSES_100: "bug_slower_responses_100ms",
  BUG_SLOWER_RESPONSES_500: "bug_slower_responses_500ms",
  BUG_SLOWER_RESPONSES_1000: "bug_slower_responses_1000ms",
  BUG_SLOWER_RESPONSES_2500: "bug_slower_responses_2500ms",
  BUG_DISABLE_MODULE_COMMENTS: "bug_disable_module_comments",
  BUG_DISABLE_MODULE_ARTICLES: "bug_disable_module_articles",
  BUG_DISABLE_MODULE_USERS: "bug_disable_module_users",
  BUG_DISABLE_MODULE_AUTH: "bug_disable_module_auth",
};

const FeatureFlagConfigKeys = {
  FEATURE_LIKES: "feature_likes",
  FEATURE_FILES: "feature_files",
  FEATURE_ONLY_BACKEND: "feature_only_backend",
  FEATURE_LABELS: "feature_labels",
  FEATURE_CACHE_CONTROL_NO_STORE: "feature_cache_control_no_store",
  FEATURE_VISITS: "feature_visits",
  FEATURE_USER_BOOKMARK_ARTICLES: "feature_user_bookmark_articles",
  FEATURE_INFINITE_SCROLL_ARTICLES: "feature_infinite_scroll_articles",
};

module.exports = {
  LogLevels,
  ConfigKeys,
  BugConfigKeys,
  FeatureFlagConfigKeys,
};
