const { generateUuid } = require("../../../helpers/helpers");

const sampleUsers = [
  {
    id: generateUuid(),
    username: "JohnDoe",
    email: "john.doe@test.test",
    password: "1234",
    fullName: "John Doe",
    profilePic: "/data/users/4b78d31b-637d-4f44-8d82-36b8a08ecbbe.jpg",
    bio: "I love photography and nature photography. I work as a software engineer and enjoy coding in my free time.",
    createdAt: new Date(Date.now() - 62 * 60 * 60 * 1000).toISOString(),
    followers: [],
    following: [],
  },
  {
    id: generateUuid(),
    username: "JaneDoe",
    email: "jane.doe@test.test",
    password: "qwer",
    fullName: "Test User 2",
    profilePic: "/data/users/444459e4-73f8-4599-a7e3-23849bbf3ae7.jpg",
    bio: "I like to test things. My favorite book is 'The Hitchhiker's Guide to the Galaxy'.",
    createdAt: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
    followers: [],
    following: [],
  },
  {
    id: generateUuid(),
    username: "BobSmith",
    email: "bob.smith@test.test",
    password: "5678",
    fullName: "Bob Smith Junior",
    profilePic: "/data/users/e0af6e4f-3e7c-4692-85a2-be9b5b9efc24.jpg",
    bio: "I love to travel and explore new places. My favorite food is sushi.",
    createdAt: new Date(Date.now() - 59 * 60 * 60 * 1000).toISOString(),
    followers: [],
    following: [],
  },
  {
    id: generateUuid(),
    username: "JanKowalski",
    email: "jan.kowalski@test.test",
    password: "abcd",
    fullName: "Jan Kowalski",
    profilePic: "/data/users/e1fd1368-1715-4ffa-8487-d537c7fb6445.jpg",
    bio: "I enjoy photography and capturing moments. My favorite place is the mountains.",
    createdAt: new Date(Date.now() - 58 * 60 * 60 * 1000).toISOString(),
    followers: [],
    following: [],
  },
];

const samplePosts = [
  {
    id: generateUuid(),
    userId: sampleUsers[0].id,
    imageUrl: "https://picsum.photos/600/600?random=1",
    caption: "Beautiful sunset!",
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[1].id,
    imageUrl: "https://picsum.photos/600/600?random=2",
    caption: "Delicious food!",
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[0].id,
    imageUrl: "https://picsum.photos/600/600?random=3",
    caption: "Amazing landscape!",
    createdAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[1].id,
    imageUrl: "https://picsum.photos/600/600?random=4",
    caption: "Cute puppy!",
    createdAt: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[0].id,
    imageUrl: "https://picsum.photos/600/600?random=5",
    caption: "Beautiful flowers!",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[2].id,
    imageUrl: "https://picsum.photos/600/600?random=6",
    caption: "Stunning mountain view!",
    createdAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[3].id,
    imageUrl: "https://picsum.photos/600/600?random=7",
    caption: "Serene beach!",
    createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[2].id,
    imageUrl: "https://picsum.photos/600/600?random=8",
    caption: "Gorgeous city skyline!",
    createdAt: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[3].id,
    imageUrl: "https://picsum.photos/600/600?random=9",
    caption: "Charming village!",
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[1].id,
    imageUrl: "https://picsum.photos/600/600?random=10",
    caption: "Adventurous hiking trip! I love nature and exploring new places with my friends.",
    createdAt: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[0].id,
    imageUrl: "https://picsum.photos/600/600?random=11",
    caption: "Relaxing at the beach. Nothing beats a day in the sun with good company.",
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[2].id,
    imageUrl: "https://picsum.photos/600/600?random=12",
    caption: "Exploring the city. I love discovering new places and cultures.",
    createdAt: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
  {
    id: generateUuid(),
    userId: sampleUsers[3].id,
    imageUrl: "https://picsum.photos/600/600?random=13",
    caption: "A day in the mountains. The fresh air and stunning views are unbeatable.",
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    likes: [],
    comments: [],
  },
];

const sampleComments = [
  {
    id: generateUuid(),
    postId: samplePosts[0].id,
    userId: sampleUsers[1].id,
    text: "Wow, amazing!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[1].id,
    userId: sampleUsers[0].id,
    text: "Looks delicious!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[2].id,
    userId: sampleUsers[1].id,
    text: "I love this!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[3].id,
    userId: sampleUsers[0].id,
    text: "So cute!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[4].id,
    userId: sampleUsers[2].id,
    text: "Beautiful!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[5].id,
    userId: sampleUsers[3].id,
    text: "Stunning view!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[6].id,
    userId: sampleUsers[3].id,
    text: "Serene beach!",
    createdAt: new Date().toISOString(),
  },
];

const sampleLikes = [
  {
    id: generateUuid(),
    postId: samplePosts[0].id,
    userId: sampleUsers[1].id,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[1].id,
    userId: sampleUsers[0].id,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[2].id,
    userId: sampleUsers[1].id,
    text: "I love this!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[3].id,
    userId: sampleUsers[0].id,
    text: "So cute!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[4].id,
    userId: sampleUsers[2].id,
    text: "Beautiful!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[5].id,
    userId: sampleUsers[3].id,
    text: "Stunning view!",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateUuid(),
    postId: samplePosts[6].id,
    userId: sampleUsers[3].id,
    text: "Serene beach!",
    createdAt: new Date().toISOString(),
  },
];

module.exports = {
  sampleUsers,
  samplePosts,
  sampleComments,
  sampleLikes,
};
