const mockData = {
  // Role definitions
  roles: {
    STUDENT: "student",
    INSTRUCTOR: "instructor",
    ADMIN: "admin",
  },

  lessonTypes: {
    VIDEO: "video",
    READING: "reading",
    QUIZ: "quiz",
    ASSIGNMENT: "assignment",
  },

  // Role permissions mapping
  rolePermissions: {
    student: ["view_courses", "enroll_courses", "view_own_progress", "submit_assignments"],
    instructor: [
      "view_courses",
      "create_courses",
      "edit_own_courses",
      "view_student_progress",
      "grade_assignments",
      "view_course_analytics",
    ],
    admin: ["view_courses", "manage_all_courses", "manage_users", "manage_roles", "view_analytics", "system_settings"],
  },

  // Users data
  users: [
    {
      id: 1,
      username: "user",
      email: "michael.scott@test.test.com",
      password: "demo",
      firstName: "Michael",
      lastName: "Scott",
      avatar: "..\\data\\users\\face_1713017873.9196286_m_1.jpg",
      joinDate: "2023-05-15",
      role: "student",
      funds: 220.02,
    },
    {
      id: 2,
      username: "john_doe",
      email: "john.doe@test.test.com",
      password: "demo",
      firstName: "John",
      lastName: "Doe",
      avatar: "..\\data\\users\\face_1713017346.0038195_m_1.jpg",
      joinDate: "2023-01-15",
      role: "instructor",
    },
    {
      id: 3,
      username: "jane_smith",
      email: "jane_smith@test.test.com",
      password: "demo",
      firstName: "Jane",
      lastName: "Smith",
      avatar: "..\\data\\users\\face_1714589705_f.jpg",
      joinDate: "2023-02-15",
      role: "student",
    },
    {
      id: 4,
      username: "bob_ross",
      email: "bob_ross@@test.test.com",
      password: "demo",
      firstName: "Bob",
      lastName: "Ross",
      avatar: "..\\data\\users\\face_1703527925.6898403_1_m.jpg",
      joinDate: "2023-03-15",
      role: "student",
    },
    {
      id: 5,
      username: "jane_doe",
      email: "jane_doe@@test.test.com",
      password: "demo",
      firstName: "Jane",
      lastName: "Doe",
      avatar: "..\\data\\users\\face_1714589623_f.jpg",
      joinDate: "2023-04-15",
      role: "student",
    },
    {
      id: 6,
      username: "jim_halpert",
      email: "jim_halpert@@test.test.com",
      password: "demo",
      firstName: "Jim",
      lastName: "Halpert",
      avatar: "..\\data\\users\\face_1713017654.0461617_m_1.jpg",
      joinDate: "2023-04-15",
      role: "student",
    },
    {
      id: 7,
      username: "pam_beesly",
      email: "pam_beesly@@test.test.com",
      password: "demo",
      firstName: "Pam",
      lastName: "Beesly",
      avatar: "..\\data\\users\\face_1713018024.9049351_f_1.jpg",
      joinDate: "2023-04-15",
      role: "student",
    },
    {
      id: 8,
      username: "andy_bernard",
      email: "andy_bernard@@test.test.com",
      password: "demo",
      firstName: "Andy",
      lastName: "Bernard",
      avatar: "..\\data\\users\\face_1713018044.62676_m_1.jpg",
      joinDate: "2023-04-15",
      role: "student",
    },
    {
      id: 9,
      username: "dwight_schrute",
      email: "dwight_schrute@@test.test.com",
      password: "demo",
      firstName: "Dwight",
      lastName: "Schrute",
      avatar: "..\\data\\users\\face_1713018046.9542458_m_1.jpg",
      joinDate: "2023-04-15",
      role: "student",
    },
    {
      id: 10,
      username: "james_sunderland",
      email: "james_sunderland@@test.test.com",
      password: "demo",
      firstName: "James",
      lastName: "Sunderland",
      avatar: "..\\data\\users\\face_1714589459.6969566_m.jpg",
      joinDate: "2023-04-15",
      role: "instructor",
    },
    {
      id: 11,
      username: "angela_martin",
      email: "angela_martin@@test.test.com",
      password: "demo",
      firstName: "Angela",
      lastName: "Martin",
      avatar: "..\\data\\users\\face_1713017873.9196286_m_1.jpg",
      joinDate: "2023-04-15",
      role: "student",
    },
    {
      id: 12,
      username: "Maria Garcia",
      email: "maria@@test.test.com",
      password: "demo",
      firstName: "Maria",
      lastName: "Garcia",
      avatar: "..\\data\\users\\face_1713017873.9196286_m_1.jpg",
      joinDate: "2023-04-15",
      role: "student",
    },
    // Add admin user
    {
      id: 999,
      username: "admin",
      email: "admin@test.test.com",
      password: "admin123",
      firstName: "System",
      lastName: "Admin",
      avatar: "..\\data\\users\\admin.jpg",
      joinDate: "2023-01-01",
      role: "admin",
    },
  ],

  // Course catalog
  courses: [
    {
      id: 1,
      title: "Introduction to Web Development",
      description:
        "Learn the fundamentals of web development including HTML, CSS, and JavaScript. Perfect for beginners wanting to start their web development journey.",
      thumbnail: "..\\data\\learning\\courses\\web-dev.jpg",
      instructor: "John Doe",
      instructorId: 2,
      duration: "8 weeks",
      totalHours: 24,
      level: "Beginner",
      students: 0,
      rating: 0,
      tags: ["HTML", "CSS", "JavaScript"],
      prerequisites: [],
      price: 49.99,
      learningObjectives: [
        "Build complete web applications from scratch",
        "Master HTML5, CSS3, and modern JavaScript",
        "Understand responsive design principles",
        "Create interactive user interfaces",
        "Learn web development best practices",
        "Implement modern web standards",
      ],
    },
    {
      id: 2,
      title: "Advanced JavaScript Programming",
      description:
        "Master modern JavaScript features, async programming, and advanced patterns. Take your JavaScript skills to the next level.",
      thumbnail: "..\\data\\learning\\courses\\js-advanced.jpg",
      instructor: "John Doe",
      instructorId: 2,
      duration: "10 weeks",
      totalHours: 30,
      level: "Advanced",
      students: 0,
      rating: 0,
      tags: ["JavaScript", "ES6+", "Async"],
      prerequisites: ["Basic JavaScript"],
      price: 79.99,
      learningObjectives: [
        "Master advanced JavaScript concepts",
        "Build complex applications using modern JS",
        "Implement async programming patterns",
        "Use modern ES6+ features effectively",
        "Create scalable application architectures",
        "Debug and optimize JavaScript code",
      ],
    },
    {
      id: 3,
      title: "React.js Fundamentals",
      description: "Build modern web applications with React. Learn components, state management, and best practices.",
      thumbnail: "..\\data\\learning\\courses\\react.jpg",
      instructor: "John Doe",
      instructorId: 2,
      duration: "12 weeks",
      totalHours: 36,
      level: "Intermediate",
      students: 0,
      rating: 0,
      tags: ["React", "JavaScript", "Web Development"],
      prerequisites: ["JavaScript"],
      price: 89.99,
      learningObjectives: [
        "Build modern React applications",
        "Master component-based architecture",
        "Implement state management patterns",
        "Create reusable React components",
        "Handle routing and navigation",
        "Optimize React application performance",
      ],
    },
    {
      id: 4,
      title: "Playwright Automation Testing",
      description:
        "Learn end-to-end testing with Playwright. Automate browser interactions, test web applications, and write reliable tests.",
      thumbnail: "..\\data\\learning\\courses\\playwright.jpg",
      instructor: "John Doe",
      instructorId: 2,
      duration: "6 weeks",
      totalHours: 18,
      level: "Intermediate",
      students: 0,
      rating: 0,
      tags: ["Playwright", "Testing", "Automation"],
      prerequisites: ["JavaScript", "Testing Basics"],
      price: 129.99,
      learningObjectives: [
        "Master Playwright automation testing",
        "Automate browser interactions",
        "Write reliable end-to-end tests",
        "Test web applications effectively",
        "Debug and optimize test scripts",
        "Implement testing best practices",
      ],
    },
    {
      id: 5,
      title: "Python Programming Basics",
      description:
        "Learn the basics of Python programming. Perfect for beginners wanting to start their coding journey with Python.",
      thumbnail: "..\\data\\learning\\courses\\python-basics.jpg",
      instructor: "James Sunderland",
      instructorId: 10,
      duration: "2 weeks",
      totalHours: 1,
      level: "Beginner",
      students: 0,
      rating: 0,
      tags: ["Python", "Programming", "Basics"],
      prerequisites: [],
      price: 59.99,
      learningObjectives: [
        "Master Python programming basics",
        "Understand Python syntax and semantics",
        "Learn data types and structures",
        "Implement Python control flow",
        "Create Python scripts and programs",
        "Debug and optimize Python code",
      ],
    },
    {
      id: 6,
      title: "Introduction to Java Programming",
      description:
        "Learn the fundamentals of Java programming. Perfect for beginners wanting to start their coding journey with Java.",
      thumbnail: "..\\data\\learning\\courses\\java-basics.jpg",
      instructor: "James Sunderland",
      instructorId: 10,
      duration: "4 weeks",
      totalHours: 12,
      level: "Beginner",
      students: 0,
      rating: 0,
      tags: ["Java", "Programming", "Basics"],
      prerequisites: [],
      price: 69.99,
      learningObjectives: [
        "Master Java programming basics",
        "Understand Java syntax and semantics",
        "Learn data types and structures",
        "Implement Java control flow",
        "Create Java scripts and programs",
        "Debug and optimize Java code",
      ],
    },
    {
      id: 7,
      title: "Manual Testing Fundamentals",
      description:
        "Learn the fundamentals of manual testing. Perfect for beginners wanting to start their testing journey with manual testing.",
      thumbnail: "..\\data\\learning\\courses\\manual-testing.jpg",
      instructor: "James Sunderland",
      instructorId: 10,
      duration: "2 weeks",
      totalHours: 1,
      level: "Beginner",
      students: 0,
      rating: 0,
      tags: ["Testing", "Manual", "Basics"],
      prerequisites: [],
      price: 0,
      learningObjectives: [
        "Master manual testing fundamentals",
        "Understand testing concepts and principles",
        "Learn testing techniques and strategies",
        "Implement manual testing best practices",
        "Create test cases and test plans",
        "Report and track software defects",
      ],
    },
    {
      id: 8,
      title: "AI in Testing",
      description:
        "Learn the fundamentals of AI in testing. Perfect for beginners wanting to start their testing journey with AI in testing.",
      thumbnail: "..\\data\\learning\\courses\\ai-testing.jpg",
      instructor: "James Sunderland",
      instructorId: 10,
      duration: "2 weeks",
      totalHours: 1,
      level: "Beginner",
      students: 0,
      rating: 0,
      tags: ["Testing", "AI", "Basics"],
      prerequisites: [],
      price: 159.99,
      learningObjectives: [
        "Master AI in testing fundamentals",
        "Understand AI testing concepts and principles",
        "Learn AI testing techniques and strategies",
        "Implement AI testing best practices",
        "Create AI test cases and test plans",
        "Report and track AI software defects",
      ],
    },
  ],

  // User enrollments with progress
  userEnrollments: [
    {
      id: 1,
      userId: 1,
      courseId: 1,
      enrollmentDate: "2024-06-01",
      lastAccessed: "2024-07-25",
      progress: 100,
      completed: true,
      certificateIssued: true,
      completionDate: "2024-06-30",
    },
    {
      id: 2,
      userId: 1,
      courseId: 2,
      enrollmentDate: "2024-07-01",
      lastAccessed: "2024-07-24",
      progress: 60,
      completed: false,
    },
    {
      id: 3,
      userId: 3,
      courseId: 1,
      enrollmentDate: "2024-07-15",
      lastAccessed: "2024-07-25",
      progress: 25,
      completed: false,
    },
    {
      id: 4,
      userId: 3,
      courseId: 2,
      enrollmentDate: "2024-07-20",
      lastAccessed: "2024-07-25",
      progress: 0,
      completed: false,
    },
    {
      id: 5,
      userId: 3,
      courseId: 3,
      enrollmentDate: "2024-07-25",
      lastAccessed: "2024-07-25",
      progress: 0,
      completed: false,
    },
    {
      id: 6,
      userId: 3,
      courseId: 4,
      enrollmentDate: "2024-07-25",
      lastAccessed: "2024-07-25",
      progress: 0,
      completed: false,
    },
    {
      id: 7,
      userId: 4,
      courseId: 4,
      enrollmentDate: "2024-07-25",
      lastAccessed: "2024-07-25",
      progress: 0,
      completed: false,
    },
    {
      id: 8,
      userId: 5,
      courseId: 1,
      enrollmentDate: "2024-07-25",
      lastAccessed: "2024-07-25",
      progress: 0,
      completed: false,
    },
    {
      id: 9,
      userId: 5,
      courseId: 2,
      enrollmentDate: "2024-09-12",
      lastAccessed: "2024-09-12",
      progress: 0,
      completed: false,
    },
    {
      id: 10,
      userId: 6,
      courseId: 1,
      enrollmentDate: "2024-10-10",
      lastAccessed: "2024-10-10",
      progress: 0,
      completed: false,
    },
    {
      id: 11,
      userId: 6,
      courseId: 2,
      enrollmentDate: "2024-12-25",
      lastAccessed: "2024-12-25",
      progress: 0,
      completed: false,
    },
    {
      id: 12,
      userId: 7,
      courseId: 1,
      enrollmentDate: "2025-01-17",
      lastAccessed: "2025-01-17",
      progress: 0,
      completed: false,
    },
    {
      id: 13,
      userId: 8,
      courseId: 1,
      enrollmentDate: "2025-02-10",
      lastAccessed: "2025-02-11",
      progress: 0,
      completed: false,
    },
    {
      id: 14,
      userId: 9,
      courseId: 1,
      enrollmentDate: "2025-02-11",
      lastAccessed: "2025-02-11",
      progress: 0,
      completed: false,
    },
    {
      id: 15,
      userId: 10,
      courseId: 1,
      enrollmentDate: "2025-02-11",
      lastAccessed: "2025-02-11",
      progress: 0,
      completed: false,
    },
  ],

  // User progress tracking
  lessonProgress: [
    {
      userId: 1,
      courseId: 1,
      lessonId: 1,
      completed: true,
      completedAt: "2023-06-15T10:30:00Z",
      score: null,
    },
    {
      userId: 1,
      courseId: 1,
      lessonId: 2,
      completed: true,
      completedAt: "2023-06-16T14:20:00Z",
      score: null,
    },
    {
      userId: 1,
      courseId: 1,
      lessonId: 3,
      completed: true,
      completedAt: "2023-06-17T09:45:00Z",
      score: 90,
    },
  ],

  // Certificates with user reference
  certificates: [
    {
      id: 1,
      userId: 1,
      courseId: 1,
      issueDate: "2023-06-30",
      certificateNumber: "CERT-2023-001",
      uuid: "550e8400-e29b-41d4-a716-446655440000",
      courseTitle: "Introduction to Web Development",
      recipientName: "Michael Scott",
      issuedBy: "John Doe",
    },
  ],

  // Course content
  courseLessons: {
    1: [
      {
        id: 1,
        title: "Introduction to HTML",
        type: "video",
        duration: "00:12:50",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/video1.mp4",
          transcript: "Introduction to HTML basics...",
        },
      },
      {
        id: 2,
        title: "HTML Structure and Elements",
        type: "reading",
        duration: "00:15:00",
        completed: false,
        content: {
          text: "The basic structure of an HTML document...",
          resources: ["HTML5 Specification", "MDN Documentation"],
        },
      },
      {
        id: 3,
        title: "HTML Fundamentals Quiz",
        type: "quiz",
        completed: true,
        content: {
          questions: [
            {
              question: "What does HTML stand for?",
              options: ["Hypertext Markup Language", "High-Level Text Language", "Hyperlink and Text Markup Language"],
              correct: 0,
            },
            {
              question: "Which tag is used for creating a paragraph?",
              options: ["p", "paragraph", "text"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 4,
        title: "Working with Forms",
        type: "video",
        duration: "00:12:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/video2.mp4",
          transcript: "Learn how to create HTML forms...",
        },
      },
      {
        id: 5,
        title: "CSS Integration",
        type: "reading",
        duration: "00:21:00",
        completed: false,
        content: {
          text: "Learn how to style your HTML with CSS...",
          resources: ["CSS Guide", "Styling Best Practices"],
        },
      },
      {
        id: 6,
        title: "Module 1 Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What does HTML stand for?",
              options: ["Hypertext Markup Language", "High-Level Text Language", "Hyperlink and Text Markup Language"],
              correct: 0,
            },
            {
              question: "Which tag is used for creating a paragraph?",
              options: ["p", "paragraph", "text"],
              correct: 0,
            },
          ],
        },
      },
    ],
    2: [
      {
        id: 1,
        title: "Modern JavaScript Features",
        type: "video",
        duration: "00:12:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/js-video1.mp4",
          transcript: "Let's explore modern JavaScript features...",
        },
      },
      {
        id: 2,
        title: "Async Programming",
        type: "reading",
        duration: "00:20:00",
        completed: false,
        content: {
          text: "Asynchronous programming in JavaScript allows you to execute code concurrently...",
          resources: ["MDN Documentation", "Async/Await Guide"],
        },
      },
      {
        id: 3,
        title: "ES6+ Features",
        type: "reading",
        duration: "00:18:00",
        completed: false,
        content: {
          text: "ES6 introduced many new features to JavaScript, such as arrow functions, classes, and modules...",
          resources: ["Babel Documentation", "ES6 Overview"],
        },
      },
      {
        id: 4,
        title: "JavaScript Basics",
        type: "video",
        duration: "00:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/js-video1.mp4",
          transcript: "Introduction to JavaScript programming...",
        },
      },
      {
        id: 5,
        title: "Variables and Data Types",
        type: "reading",
        duration: "00:20:00",
        completed: false,
        content: {
          text: "Understanding JavaScript variables and data types...",
          resources: ["JavaScript Guide", "MDN Variables"],
        },
      },
      {
        id: 6,
        title: "Functions and Scope",
        type: "video",
        duration: "00:25:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/js-video2.mp4",
          transcript: "Deep dive into JavaScript functions...",
        },
      },
      {
        id: 7,
        title: "Arrays and Objects",
        type: "reading",
        duration: "00:30:00",
        completed: false,
        content: {
          text: "Working with complex data structures...",
          resources: ["Array Methods", "Object Manipulation"],
        },
      },
      {
        id: 8,
        title: "JavaScript Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "Which operator is used for strict equality?",
              options: ["===", "==", "="],
              correct: 0,
            },
            {
              question: "What is the result of typeof []?",
              options: ["object", "array", "undefined"],
              correct: 0,
            },
          ],
        },
      },
    ],
    3: [
      {
        id: 1,
        title: "React Components",
        type: "video",
        duration: "00:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/react-video1.mp4",
          transcript: "Understanding React components...",
        },
      },
      {
        id: 2,
        title: "State Management",
        type: "reading",
        duration: "00:25:00",
        completed: false,
        content: {
          text: "State management is a crucial part of building React applications...",
          resources: ["Redux Documentation", "Context API Guide"],
        },
      },
    ],
    4: [
      {
        id: 1,
        title: "Introduction to Playwright",
        type: "video",
        duration: "00:10:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/playwright-video1.mp4",
          transcript: "Getting started with Playwright automation...",
        },
      },
      {
        id: 2,
        title: "Automating Browser Interactions",
        type: "reading",
        duration: "00:18:00",
        completed: false,
        content: {
          text: "Learn how to automate browser interactions using Playwright...",
          resources: ["Playwright Documentation", "Automated Testing Guide"],
        },
      },
      {
        id: 3,
        title: "Writing Reliable Tests",
        type: "reading",
        duration: "00:20:00",
        completed: false,
        content: {
          text: "Best practices for writing reliable end-to-end tests...",
          resources: ["Testing Strategies", "Playwright Patterns"],
        },
      },
      {
        id: 4,
        title: "Playwright Automation Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is Playwright used for?",
              options: ["Automation Testing", "Unit Testing", "Manual Testing"],
              correct: 0,
            },
            {
              question: "Which browser engines are supported by Playwright?",
              options: ["Chromium, WebKit, Firefox", "Chrome, Safari, Edge", "IE, Firefox, Opera"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "Debugging and Optimization",
        type: "video",
        duration: "00:30:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/playwright-video1.mp4",
          transcript: "Debugging and optimizing Playwright tests...",
        },
      },
      {
        id: 6,
        title: "Testing Best Practices",
        type: "video",
        duration: "00:55:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/playwright-video1.mp4",
          transcript: "Best practices for automated testing are essential for successful test automation projects...",
          resources: ["Testing Standards", "Automation Testing Principles"],
        },
      },
    ],
    5: [
      {
        id: 1,
        title: "Python Basics",
        type: "video",
        duration: "00:10:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/python-video1.mp4",
          transcript: "Introduction to Python programming...",
        },
      },
    ],
    6: [
      {
        id: 1,
        title: "Java Basics",
        type: "video",
        duration: "00:20:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/java-video1.mp4",
          transcript: "Introduction to Java programming...",
        },
      },
      {
        id: 2,
        title: "Java Syntax and Semantics",
        type: "reading",
        duration: "00:35:00",
        completed: false,
        content: {
          text: "Understanding Java syntax and semantics...",
          resources: ["Java Documentation", "Java Basics Guide"],
        },
      },
      {
        id: 3,
        title: "Java Control Flow",
        type: "reading",
        duration: "00:44:00",
        completed: false,
        content: {
          text: "Learn how to control program flow in Java...",
          resources: ["Java Loops", "Decision Making"],
        },
      },
      {
        id: 4,
        title: "Java Basics Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is Java?",
              options: ["Programming Language", "Coffee", "Tea"],
              correct: 0,
            },
            {
              question: "Which of the following is a Java keyword?",
              options: ["class", "method", "variable"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "Java Methods",
        type: "video",
        duration: "00:53:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/java-video1.mp4",
          transcript: "Methods in Java programming language...",
        },
      },
      {
        id: 6,
        title: "Java Classes and Objects",
        type: "reading",
        duration: "00:49:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/java-video1.mp4",
          transcript:
            "Classes and objects are fundamental concepts in object-oriented programming (OOP) languages like Java...",
        },
      },
      {
        id: 7,
        title: "Java Inheritance",
        type: "video",
        duration: "00:35:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/java-video1.mp4",
          transcript:
            "Inheritance is a key feature of object-oriented programming. Learn how to use it in Java programming language...",
        },
      },
      {
        id: 8,
        title: "Java Basics Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is Java?",
              options: ["Programming Language", "Coffee", "Tea"],
              correct: 0,
            },
            {
              question: "Which of the following is a Java keyword?",
              options: ["class", "method", "variable"],
              correct: 0,
            },
            {
              question: "What is a class in Java?",
              options: ["A method", "A blueprint for objects", "A variable"],
              correct: 1,
            },
            {
              question: "What is an object in Java?",
              options: ["An instance of a class", "A method", "A variable"],
              correct: 0,
            },
            {
              question: "What is inheritance in Java?",
              options: ["Reusing code", "Creating new classes", "Both of the above"],
              correct: 2,
            },
          ],
        },
      },
    ],
    7: [
      {
        id: 1,
        title: "Manual Testing Fundamentals",
        type: "video",
        duration: "00:10:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Introduction to manual testing...",
        },
      },
      {
        id: 2,
        title: "Testing Techniques",
        type: "video",
        duration: "00:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Learn manual testing techniques and strategies...",
          resources: ["Testing Guide", "Manual Testing Best Practices"],
        },
      },
      {
        id: 3,
        title: "Creating Test Cases",
        type: "video",
        duration: "00:20:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "How to create effective test cases...",
          resources: ["Test Case Examples", "Test Case Templates"],
        },
      },
      {
        id: 4,
        title: "Manual Testing Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is manual testing?",
              options: ["Testing by humans", "Automated testing", "Unit testing"],
              correct: 0,
            },
            {
              question: "What is a test case?",
              options: ["A set of conditions", "A test script", "A test plan"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "Reporting Defects",
        type: "video",
        duration: "00:25:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "How to report and track software defects...",
          resources: ["Defect Tracking Tools", "Defect Reporting Guidelines"],
        },
      },
      {
        id: 6,
        title: "Manual Testing Best Practices",
        type: "video",
        duration: "00:30:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Best practices for manual testing...",
          resources: ["Testing Standards", "Manual Testing Principles"],
        },
      },
      {
        id: 7,
        title: "Manual Testing Techniques",
        type: "video",
        duration: "00:35:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Effective manual testing techniques...",
          resources: ["Testing Strategies", "Manual Testing Patterns"],
        },
      },
      {
        id: 8,
        title: "Manual Testing Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What are the benefits of manual testing?",
              options: ["Human judgment", "Flexibility", "All of the above"],
              correct: 2,
            },
            {
              question: "What is a test case?",
              options: ["A set of conditions", "A test script", "A test plan"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 9,
        title: "Manual Testing Patterns",
        type: "video",
        duration: "00:40:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Effective manual testing techniques and patterns...",
          resources: ["Testing Strategies", "Manual Testing Patterns"],
        },
      },
      {
        id: 10,
        title: "Manual Testing Strategies",
        type: "video",
        duration: "00:45:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Effective manual testing techniques...",
          resources: ["Testing Strategies", "Manual Testing Patterns"],
        },
      },
      {
        id: 11,
        title: "Manual Testing Principles",
        type: "video",
        duration: "00:50:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Effective manual testing techniques...",
          resources: ["Testing Strategies", "Manual Testing Patterns"],
        },
      },
    ],
    8: [
      {
        id: 1,
        title: "AI in Testing Fundamentals",
        type: "video",
        duration: "05:34:10",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Introduction to AI in testing...",
        },
      },
      {
        id: 2,
        title: "AI Testing Techniques",
        type: "video",
        duration: "06:45:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Learn AI testing techniques and strategies...",
          resources: ["Testing Guide", "AI Testing Best Practices"],
        },
      },
      {
        id: 3,
        title: "AI Testing Patterns",
        type: "video",
        duration: "07:30:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Effective AI testing techniques and patterns...",
          resources: ["Testing Strategies", "AI Testing Patterns"],
        },
      },
      {
        id: 4,
        title: "AI Testing Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is AI in testing?",
              options: ["Testing by machines", "Automated testing", "Manual testing"],
              correct: 0,
            },
            {
              question: "What is a test case?",
              options: ["A set of conditions", "A test script", "A test plan"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "AI Testing Strategies",
        type: "video",
        duration: "08:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Effective AI testing techniques...",
          resources: ["Testing Strategies", "AI Testing Patterns"],
        },
      },
      {
        id: 6,
        title: "AI Testing Best Practices",
        type: "video",
        duration: "09:00:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Best practices for AI testing...",
          resources: ["Testing Standards", "AI Testing Principles"],
        },
      },
      {
        id: 7,
        title: "AI Testing Techniques",
        type: "video",
        duration: "09:45:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Effective AI testing techniques...",
          resources: ["Testing Strategies", "AI Testing Patterns"],
        },
      },
    ],
  },

  // Quiz attempts tracking
  quizAttempts: [
    {
      id: 1,
      userId: 1,
      courseId: 1,
      lessonId: 3,
      attemptDate: "2023-06-17T09:45:00Z",
      score: 90,
      passed: true,
      answers: [0, 0], // User's selected answers
    },
  ],

  // User statistics cache
  userStats: [
    {
      userId: 1,
      coursesInProgress: 1,
      completedCourses: 1,
      totalHours: 28,
      totalCertificates: 1,
      lastUpdated: "2023-07-25T12:00:00Z",
    },
  ],

  failedLoginAttempts: {
    // Structure: { email: { count: number, lastAttempt: string } }
  },

  userRatings: [
    {
      userId: 3,
      courseId: 1,
      rating: 5,
      comment: "Great course, learned a lot!",
      createdAt: "2024-07-25T12:00:00Z",
    },
    {
      userId: 3,
      courseId: 2,
      rating: 4,
      comment: "Good content, could be more challenging.",
      createdAt: "2024-08-25T12:00:00Z",
    },
    {
      userId: 3,
      courseId: 3,
      rating: 3,
      comment: "Decent course, but could use more examples.",
      createdAt: "2024-09-25T12:00:00Z",
    },
    {
      userId: 3,
      courseId: 4,
      rating: 5,
      comment: "Excellent course, very informative!",
      createdAt: "2024-10-25T12:00:00Z",
    },
    {
      userId: 4,
      courseId: 4,
      rating: 5,
      comment: "Great course, learned a lot!",
      createdAt: "2024-07-25T12:00:00Z",
    },
    {
      userId: 5,
      courseId: 1,
      rating: 4,
      comment: "Good content, could be more challenging. Also, more examples would be helpful.",
      createdAt: "2024-08-25T12:00:00Z",
    },
    {
      userId: 5,
      courseId: 2,
      rating: 3,
      comment: "Well... it was okay.",
      createdAt: "2024-09-25T12:00:00Z",
    },
    {
      userId: 6,
      courseId: 1,
      rating: 4,
      comment: "Excellent course, very informative! I learned a lot from this course. Highly recommended.",
      createdAt: "2024-10-25T12:00:00Z",
    },
    {
      userId: 7,
      courseId: 1,
      rating: 2,
      comment: "It was very basic, not what I expected.",
      createdAt: "2024-07-25T12:00:00Z",
    },
    {
      userId: 8,
      courseId: 1,
      rating: 4,
      comment: "Good content, could be more challenging.",
      createdAt: "2024-08-25T12:00:00Z",
    },
    {
      userId: 9,
      courseId: 1,
      rating: 1,
      comment: "Not a good course, very basic content.",
      createdAt: "2025-02-13T12:35:00Z",
    },
  ],

  // Add funds transaction history
  fundsHistory: [
    {
      userId: 1,
      amount: 50.0,
      type: "credit",
      timestamp: "2023-11-01T10:30:00Z",
      description: "Account top up",
    },
    {
      userId: 1,
      amount: 49.99,
      type: "debit",
      timestamp: "2023-11-02T14:20:00Z",
      description: "Course enrollment: Introduction to Web Development",
    },
    {
      userId: 1,
      amount: 100.0,
      type: "credit",
      timestamp: "2023-11-03T09:45:00Z",
      description: "Account top up",
    },
    {
      userId: 1,
      amount: 79.99,
      type: "debit",
      timestamp: "2023-11-04T16:30:00Z",
      description: "Course enrollment: Advanced JavaScript Programming",
    },
    {
      userId: 1,
      amount: 100.0,
      type: "credit",
      timestamp: "2024-12-03T09:45:00Z",
      description: "Account top up",
    },
  ],
};

// Export the data
module.exports = mockData;
