const mockData = {
  // Role definitions
  roles: {
    STUDENT: "student",
    INSTRUCTOR: "instructor",
    ADMIN: "admin",
  },

  lessonTypes: {
    VIDEO: "video",
    READING: "reading",
    QUIZ: "quiz",
    ASSIGNMENT: "assignment",
  },

  // Role permissions mapping
  rolePermissions: {
    student: ["view_courses", "enroll_courses", "view_own_progress", "submit_assignments"],
    instructor: [
      "view_courses",
      "create_courses",
      "edit_own_courses",
      "view_student_progress",
      "grade_assignments",
      "view_course_analytics",
    ],
    admin: ["view_courses", "manage_all_courses", "manage_users", "manage_roles", "view_analytics", "system_settings"],
  },

  // Users data
  users: [
    {
      id: 0,
      username: "admin",
      email: "shodan.citadel@test.test.test",
      password: "1234",
      firstName: "Shodan",
      lastName: "Citadel",
      avatar: "..\\data\\users\\face_shodan.jpg",
      joinDate: "2023-05-15",
      role: "admin",
    },
    {
      id: 1,
      username: "sarah_mitchell",
      email: "sarah.mitchell@test.test.test",
      password: "demo",
      firstName: "Sarah",
      lastName: "Mitchell",
      avatar: "..\\data\\users\\face_1714589421_f.jpg",
      joinDate: "2023-10-15",
      role: "student",
      funds: 450.75,
      isPublic: false,
    },
    {
      id: 2,
      username: "david_chen",
      email: "david.chen@test.test.test",
      password: "demo",
      firstName: "David",
      lastName: "Chen",
      avatar: "..\\data\\users\\face_1714589520.9587314_m.jpg",
      joinDate: "2023-11-05",
      role: "instructor",
      isPublic: false,
    },
    {
      id: 3,
      username: "emily_zhang",
      email: "emily.zhang@test.test.test",
      password: "demo",
      firstName: "Emily",
      lastName: "Zhang",
      avatar: "..\\data\\users\\face_1714589605_f.jpg",
      joinDate: "2023-11-20",
      role: "student",
      isPublic: false,
    },
    {
      id: 4,
      username: "marcus_weber",
      email: "marcus.weber@test.test.test",
      password: "demo",
      firstName: "Marcus",
      lastName: "Weber",
      avatar: "..\\data\\users\\face_1714589597.569859_m.jpg",
      joinDate: "2023-12-01",
      role: "student",
    },
    {
      id: 5,
      username: "sophia_patel",
      email: "sophia.patel@test.test.test",
      password: "demo",
      firstName: "Sophia",
      lastName: "Patel",
      avatar: "..\\data\\users\\face_1714589623_f.jpg",
      joinDate: "2023-12-15",
      role: "student",
    },
    {
      id: 6,
      username: "ryan_thompson",
      email: "ryan.thompson@test.test.test",
      password: "demo",
      firstName: "Ryan",
      lastName: "Thompson",
      avatar: "..\\data\\users\\face_1714589611.2953043_m.jpg",
      joinDate: "2024-01-05",
      role: "student",
    },
    {
      id: 7,
      username: "olivia_brown",
      email: "olivia.brown@test.test.test",
      password: "demo",
      firstName: "Olivia",
      lastName: "Brown",
      avatar: "..\\data\\users\\face_1714589702_f.jpg",
      joinDate: "2024-01-15",
      role: "student",
    },
    {
      id: 8,
      username: "james_wilson",
      email: "james.wilson@test.test.test",
      password: "demo",
      firstName: "James",
      lastName: "Wilson",
      avatar: "..\\data\\users\\face_1714589711.4612474_m.jpg",
      joinDate: "2024-01-20",
      role: "student",
    },
    {
      id: 9,
      username: "dr_anderson",
      email: "lisa.anderson@test.test.test",
      password: "demo",
      firstName: "Lisa",
      lastName: "Anderson",
      avatar: "..\\data\\users\\face_1714589682.19299_m.jpg",
      joinDate: "2024-01-25",
      role: "instructor",
    },
    {
      id: 10,
      username: "prof_carter",
      email: "michael.carter@test.test.test",
      password: "demo",
      firstName: "Michael",
      lastName: "Carter",
      avatar: "..\\data\\users\\face_1714589626.6606026_m.jpg",
      joinDate: "2024-02-01",
      role: "instructor",
    },
    {
      id: 11,
      username: "anna_kim",
      email: "anna.kim@test.test.test",
      password: "demo",
      firstName: "Anna",
      lastName: "Kim",
      avatar: "..\\data\\users\\face_1714589668_f.jpg",
      joinDate: "2024-02-05",
      role: "student",
    },
    {
      id: 12,
      username: "carlos_rodriguez",
      email: "carlos.r@test.test.test",
      password: "demo",
      firstName: "Carlos",
      lastName: "Rodriguez",
      avatar: "..\\data\\users\\face_1714589572.5691462_m.jpg",
      joinDate: "2024-02-10",
      role: "student",
    },
    {
      id: 13,
      username: "nina_patel",
      email: "nina.patel@test.test.test",
      password: "demo",
      firstName: "Nina",
      lastName: "Patel",
      avatar: "..\\data\\users\\face_1714589604_f.jpg",
      joinDate: "2024-02-15",
      role: "student",
    },
    {
      id: 14,
      username: "thomas_schmidt",
      email: "thomas.s@test.test.test",
      password: "demo",
      firstName: "Thomas",
      lastName: "Schmidt",
      avatar: "..\\data\\users\\face_1714589579.451615_m.jpg",
      joinDate: "2024-02-20",
      role: "student",
    },
    {
      id: 999,
      username: "sys",
      email: "admin@test.test.com",
      password: "admin123",
      firstName: "System",
      lastName: "Admin",
      avatar: "..\\data\\users\\_433a1e38-6798-4980-a421-83345e50e628_1.jpg",
      joinDate: "2023-01-01",
      role: "admin",
    },
  ],

  // Course catalog
  courses: [
    {
      id: 1,
      title: "Introduction to Web Development",
      description:
        "Learn the fundamentals of web development including HTML, CSS, and JavaScript. Perfect for beginners wanting to start their web development journey.",
      thumbnail: "..\\data\\learning\\courses\\web-dev.jpg",
      instructor: "John Doe",
      instructorId: 2,
      duration: "8 weeks",
      totalHours: 24,
      level: "Beginner",
      students: 0,
      rating: 0,
      tags: ["HTML", "CSS", "JavaScript"],
      prerequisites: [],
      price: 49.99,
      learningObjectives: [
        "Build complete web applications from scratch",
        "Master HTML5, CSS3, and modern JavaScript",
        "Understand responsive design principles",
        "Create interactive user interfaces",
        "Learn web development best practices",
        "Implement modern web standards",
      ],
    },
    {
      id: 2,
      title: "Advanced JavaScript Programming",
      description:
        "Master modern JavaScript features, async programming, and advanced patterns. Take your JavaScript skills to the next level.",
      thumbnail: "..\\data\\learning\\courses\\js-advanced.jpg",
      instructor: "John Doe",
      instructorId: 2,
      duration: "10 weeks",
      totalHours: 30,
      level: "Advanced",
      students: 0,
      rating: 0,
      tags: ["JavaScript", "ES6+", "Async"],
      prerequisites: ["Basic JavaScript"],
      price: 79.99,
      learningObjectives: [
        "Master advanced JavaScript concepts",
        "Build complex applications using modern JS",
        "Implement async programming patterns",
        "Use modern ES6+ features effectively",
        "Create scalable application architectures",
        "Debug and optimize JavaScript code",
      ],
    },
    {
      id: 3,
      title: "React.js Fundamentals",
      description: "Build modern web applications with React. Learn components, state management, and best practices.",
      thumbnail: "..\\data\\learning\\courses\\react.jpg",
      instructor: "John Doe",
      instructorId: 2,
      duration: "12 weeks",
      totalHours: 36,
      level: "Intermediate",
      students: 0,
      rating: 0,
      tags: ["React", "JavaScript", "Web Development"],
      prerequisites: ["JavaScript"],
      price: 89.99,
      learningObjectives: [
        "Build modern React applications",
        "Master component-based architecture",
        "Implement state management patterns",
        "Create reusable React components",
        "Handle routing and navigation",
        "Optimize React application performance",
      ],
    },
    {
      id: 4,
      title: "Playwright Automation Testing",
      description:
        "Learn end-to-end testing with Playwright. Automate browser interactions, test web applications, and write reliable tests.",
      thumbnail: "..\\data\\learning\\courses\\playwright.jpg",
      instructor: "John Doe",
      instructorId: 2,
      duration: "6 weeks",
      totalHours: 18,
      level: "Intermediate",
      students: 0,
      rating: 0,
      tags: ["Playwright", "Testing", "Automation"],
      prerequisites: ["JavaScript", "Testing Basics"],
      price: 129.99,
      learningObjectives: [
        "Master Playwright automation testing",
        "Automate browser interactions",
        "Write reliable end-to-end tests",
        "Test web applications effectively",
        "Debug and optimize test scripts",
        "Implement testing best practices",
      ],
    },
    {
      id: 5,
      title: "Cybersecurity Fundamentals",
      description:
        "Master essential cybersecurity concepts and practices. Learn to identify, analyze, and mitigate security threats in modern systems.",
      thumbnail: "..\\data\\learning\\courses\\_9a910bb8-4404-4f7a-91e2-4fb7edda3236.jpg",
      instructor: "Lisa Anderson",
      instructorId: 9,
      duration: "12 weeks",
      totalHours: 36,
      level: "Intermediate",
      students: 0,
      rating: 0,
      tags: ["Security", "Networking", "Cryptography", "Risk Management"],
      prerequisites: ["Basic Networking", "Linux Basics"],
      price: 159.99,
      learningObjectives: [
        "Understand security fundamentals",
        "Implement security controls",
        "Perform vulnerability assessments",
        "Master incident response",
        "Deploy security tools",
        "Develop security policies",
      ],
    },
    {
      id: 6,
      title: "Data Science and Analytics",
      description:
        "Comprehensive guide to data science, from statistical analysis to predictive modeling using Python and popular data science libraries.",
      thumbnail: "..\\data\\learning\\courses\\_5af673e8-9e10-4077-985e-54a7d7730609.jpg",
      instructor: "Michael Carter",
      instructorId: 10,
      duration: "14 weeks",
      totalHours: 42,
      level: "Advanced",
      students: 0,
      rating: 0,
      tags: ["Data Science", "Python", "Statistics", "Machine Learning"],
      prerequisites: ["Python Basics", "Statistics", "Mathematics"],
      price: 179.99,
      learningObjectives: [
        "Master data analysis techniques",
        "Implement statistical models",
        "Perform data visualization",
        "Build predictive models",
        "Handle big data processing",
        "Deploy machine learning solutions",
      ],
    },
    {
      id: 7,
      title: "Mobile App Development with React Native",
      description:
        "Build cross-platform mobile applications using React Native. Learn to create native-like experiences for iOS and Android.",
      thumbnail: "..\\data\\learning\\courses\\_db2f7fc4-01ea-48b5-80d1-43d54654563c.jpg",
      instructor: "David Chen",
      instructorId: 2,
      duration: "10 weeks",
      totalHours: 30,
      level: "Intermediate",
      students: 0,
      rating: 0,
      tags: ["React Native", "Mobile", "JavaScript", "Cross-platform"],
      prerequisites: ["JavaScript", "React"],
      price: 149.99,
      learningObjectives: [
        "Build mobile applications",
        "Implement native features",
        "Create custom components",
        "Handle state management",
        "Optimize app performance",
        "Deploy to app stores",
      ],
    },
    {
      id: 8,
      title: "Blockchain Development",
      description:
        "Learn to develop blockchain applications and smart contracts using Ethereum and Solidity. Master Web3 integration and DApp development.",
      thumbnail: "..\\data\\learning\\courses\\_7988dd9e-55d7-4995-a4c3-6046201a7eab.jpg",
      instructor: "Michael Carter",
      instructorId: 10,
      duration: "8 weeks",
      totalHours: 24,
      level: "Advanced",
      students: 0,
      rating: 0,
      tags: ["Blockchain", "Ethereum", "Solidity", "Web3"],
      prerequisites: ["JavaScript", "Basic Cryptography"],
      price: 199.99,
      learningObjectives: [
        "Develop smart contracts",
        "Build DApps",
        "Implement Web3 integration",
        "Master blockchain security",
        "Deploy to mainnet/testnet",
        "Optimize gas usage",
      ],
    },
    {
      id: 9,
      title: "UI/UX Design Principles",
      description:
        "Master modern UI/UX design principles and practices. Learn to create intuitive, accessible, and engaging user experiences.",
      thumbnail: "..\\data\\learning\\courses\\_b370ef1e-8b23-499f-9abb-9b86a2b2bf8a.jpg",
      instructor: "Lisa Anderson",
      instructorId: 9,
      duration: "6 weeks",
      totalHours: 18,
      level: "Beginner",
      students: 0,
      rating: 0,
      tags: ["UI", "UX", "Design", "Prototyping"],
      prerequisites: [],
      price: 89.99,
      learningObjectives: [
        "Master design principles",
        "Create user personas",
        "Design user flows",
        "Build interactive prototypes",
        "Conduct user research",
        "Implement accessibility",
      ],
    },
  ],

  // User enrollments with progress
  userEnrollments: [
    {
      id: 1,
      userId: 3,
      courseId: 5,
      enrollmentDate: "2024-01-15",
      lastAccessed: "2024-02-25",
      progress: 75,
      completed: false,
    },
    {
      id: 2,
      userId: 4,
      courseId: 8,
      enrollmentDate: "2024-02-01",
      lastAccessed: "2024-02-24",
      progress: 30,
      completed: false,
    },
    {
      id: 3,
      userId: 5,
      courseId: 6,
      enrollmentDate: "2024-01-20",
      lastAccessed: "2024-02-25",
      progress: 100,
      completed: true,
      certificateIssued: true,
      completionDate: "2024-02-20",
    },
    {
      id: 4,
      userId: 6,
      courseId: 7,
      enrollmentDate: "2024-02-10",
      lastAccessed: "2024-02-25",
      progress: 45,
      completed: false,
    },
    {
      id: 5,
      userId: 7,
      courseId: 9,
      enrollmentDate: "2024-02-15",
      lastAccessed: "2024-02-25",
      progress: 15,
      completed: false,
    },
    {
      id: 6,
      userId: 8,
      courseId: 10,
      enrollmentDate: "2024-01-05",
      lastAccessed: "2024-02-25",
      progress: 90,
      completed: false,
    },
    {
      id: 7,
      userId: 11,
      courseId: 12,
      enrollmentDate: "2024-02-05",
      lastAccessed: "2024-02-24",
      progress: 60,
      completed: false,
    },
    {
      id: 8,
      userId: 12,
      courseId: 14,
      enrollmentDate: "2024-02-18",
      lastAccessed: "2024-02-25",
      progress: 10,
      completed: false,
    },
    {
      id: 9,
      userId: 13,
      courseId: 11,
      enrollmentDate: "2024-01-25",
      lastAccessed: "2024-02-25",
      progress: 100,
      completed: true,
      certificateIssued: true,
      completionDate: "2024-02-23",
    },
    {
      id: 10,
      userId: 14,
      courseId: 13,
      enrollmentDate: "2024-02-12",
      lastAccessed: "2024-02-25",
      progress: 25,
      completed: false,
    },
    {
      id: 11,
      userId: 3,
      courseId: 14,
      enrollmentDate: "2024-02-01",
      lastAccessed: "2024-02-25",
      progress: 50,
      completed: false,
    },
    {
      id: 12,
      userId: 4,
      courseId: 11,
      enrollmentDate: "2024-01-15",
      lastAccessed: "2024-02-24",
      progress: 85,
      completed: false,
    },
  ],

  // User progress tracking
  lessonProgress: [
    // Completed course - userId: 5, courseId: 6 (Data Science)
    {
      userId: 5,
      courseId: 6,
      lessonId: 1,
      completed: true,
      completedAt: "2024-02-15T14:30:00Z",
    },
    {
      userId: 5,
      courseId: 6,
      lessonId: 2,
      completed: true,
      completedAt: "2024-02-16T15:45:00Z",
    },
    {
      userId: 5,
      courseId: 6,
      lessonId: 3,
      completed: true,
      completedAt: "2024-02-17T11:20:00Z",
    },
    {
      userId: 5,
      courseId: 6,
      lessonId: 4,
      completed: true,
      completedAt: "2024-02-18T16:10:00Z",
    },
    // Completed course - userId: 13, courseId: 11 (API Testing)
    {
      userId: 13,
      courseId: 11,
      lessonId: 1,
      completed: true,
      completedAt: "2024-02-19T10:15:00Z",
    },
    {
      userId: 13,
      courseId: 11,
      lessonId: 2,
      completed: true,
      completedAt: "2024-02-20T13:45:00Z",
    },
    {
      userId: 13,
      courseId: 11,
      lessonId: 3,
      completed: true,
      completedAt: "2024-02-21T15:30:00Z",
    },
    // In progress - userId: 3, courseId: 5 (Cybersecurity, 75% complete)
    {
      userId: 3,
      courseId: 5,
      lessonId: 1,
      completed: true,
      completedAt: "2024-02-20T09:30:00Z",
    },
    // In progress - userId: 4, courseId: 8 (Blockchain, 30% complete)
    {
      userId: 4,
      courseId: 8,
      lessonId: 1,
      completed: true,
      completedAt: "2024-02-15T14:20:00Z",
    },
    {
      userId: 4,
      courseId: 8,
      lessonId: 2,
      completed: true,
      completedAt: "2024-02-18T16:45:00Z",
    },
    // In progress - userId: 6, courseId: 7 (React Native, 45% complete)
    {
      userId: 6,
      courseId: 7,
      lessonId: 1,
      completed: true,
      completedAt: "2024-02-20T11:30:00Z",
    },
    {
      userId: 6,
      courseId: 7,
      lessonId: 2,
      completed: true,
      completedAt: "2024-02-22T15:20:00Z",
    },
    {
      userId: 6,
      courseId: 7,
      lessonId: 3,
      completed: true,
      completedAt: "2024-02-23T10:45:00Z",
    },
  ],

  // Certificates with user reference
  certificates: [
    {
      id: 1,
      userId: 5,
      courseId: 6,
      issueDate: "2024-02-20",
      certificateNumber: "CERT-2024-001",
      uuid: "550e8400-e29b-41d4-a716-446655440001",
      courseTitle: "Data Science and Analytics",
      recipientName: "Sophia Patel",
      issuedBy: "Michael Carter",
    },
    {
      id: 2,
      userId: 13,
      courseId: 11,
      issueDate: "2024-02-23",
      certificateNumber: "CERT-2024-002",
      uuid: "550e8400-e29b-41d4-a716-446655440002",
      courseTitle: "API Testing",
      recipientName: "Nina Patel",
      issuedBy: "Lisa Anderson",
    },
  ],

  // Course content
  courseLessons: {
    1: [
      {
        id: 1,
        title: "Introduction to HTML",
        type: "video",
        duration: "00:12:50",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/video1.mp4",
          transcript: "Introduction to HTML basics...",
        },
      },
      {
        id: 2,
        title: "HTML Structure and Elements",
        type: "reading",
        duration: "00:15:00",
        completed: false,
        content: {
          text: "The basic structure of an HTML document...",
          resources: ["HTML5 Specification", "MDN Documentation"],
        },
      },
      {
        id: 3,
        title: "HTML Fundamentals Quiz",
        type: "quiz",
        completed: true,
        content: {
          questions: [
            {
              question: "What does HTML stand for?",
              options: ["Hypertext Markup Language", "High-Level Text Language", "Hyperlink and Text Markup Language"],
              correct: 0,
            },
            {
              question: "Which tag is used for creating a paragraph?",
              options: ["p", "paragraph", "text"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 4,
        title: "Working with Forms",
        type: "video",
        duration: "00:12:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/video2.mp4",
          transcript: "Learn how to create HTML forms...",
        },
      },
      {
        id: 5,
        title: "CSS Integration",
        type: "reading",
        duration: "00:21:00",
        completed: false,
        content: {
          text: "Learn how to style your HTML with CSS...",
          resources: ["CSS Guide", "Styling Best Practices"],
        },
      },
      {
        id: 6,
        title: "Module 1 Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What does HTML stand for?",
              options: ["Hypertext Markup Language", "High-Level Text Language", "Hyperlink and Text Markup Language"],
              correct: 0,
            },
            {
              question: "Which tag is used for creating a paragraph?",
              options: ["p", "paragraph", "text"],
              correct: 0,
            },
          ],
        },
      },
    ],
    2: [
      {
        id: 1,
        title: "Modern JavaScript Features",
        type: "video",
        duration: "00:12:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/js-video1.mp4",
          transcript: "Let's explore modern JavaScript features...",
        },
      },
      {
        id: 2,
        title: "Async Programming",
        type: "reading",
        duration: "00:20:00",
        completed: false,
        content: {
          text: "Asynchronous programming in JavaScript allows you to execute code concurrently...",
          resources: ["MDN Documentation", "Async/Await Guide"],
        },
      },
      {
        id: 3,
        title: "ES6+ Features",
        type: "reading",
        duration: "00:18:00",
        completed: false,
        content: {
          text: "ES6 introduced many new features to JavaScript, such as arrow functions, classes, and modules...",
          resources: ["Babel Documentation", "ES6 Overview"],
        },
      },
      {
        id: 4,
        title: "JavaScript Basics",
        type: "video",
        duration: "00:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/js-video1.mp4",
          transcript: "Introduction to JavaScript programming...",
        },
      },
      {
        id: 5,
        title: "Variables and Data Types",
        type: "reading",
        duration: "00:20:00",
        completed: false,
        content: {
          text: "Understanding JavaScript variables and data types...",
          resources: ["JavaScript Guide", "MDN Variables"],
        },
      },
      {
        id: 6,
        title: "Functions and Scope",
        type: "video",
        duration: "00:25:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/js-video2.mp4",
          transcript: "Deep dive into JavaScript functions...",
        },
      },
      {
        id: 7,
        title: "Arrays and Objects",
        type: "reading",
        duration: "00:30:00",
        completed: false,
        content: {
          text: "Working with complex data structures...",
          resources: ["Array Methods", "Object Manipulation"],
        },
      },
      {
        id: 8,
        title: "JavaScript Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "Which operator is used for strict equality?",
              options: ["===", "==", "="],
              correct: 0,
            },
            {
              question: "What is the result of typeof []?",
              options: ["object", "array", "undefined"],
              correct: 0,
            },
          ],
        },
      },
    ],
    3: [
      {
        id: 1,
        title: "React Components",
        type: "video",
        duration: "00:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/react-video1.mp4",
          transcript: "Understanding React components...",
        },
      },
      {
        id: 2,
        title: "State Management",
        type: "reading",
        duration: "00:25:00",
        completed: false,
        content: {
          text: "State management is a crucial part of building React applications...",
          resources: ["Redux Documentation", "Context API Guide"],
        },
      },
    ],
    4: [
      {
        id: 1,
        title: "Introduction to Playwright",
        type: "video",
        duration: "00:10:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/playwright-video1.mp4",
          transcript: "Getting started with Playwright automation...",
        },
      },
      {
        id: 2,
        title: "Automating Browser Interactions",
        type: "reading",
        duration: "00:18:00",
        completed: false,
        content: {
          text: "Learn how to automate browser interactions using Playwright...",
          resources: ["Playwright Documentation", "Automated Testing Guide"],
        },
      },
      {
        id: 3,
        title: "Writing Reliable Tests",
        type: "reading",
        duration: "00:20:00",
        completed: false,
        content: {
          text: "Best practices for writing reliable end-to-end tests...",
          resources: ["Testing Strategies", "Playwright Patterns"],
        },
      },
      {
        id: 4,
        title: "Playwright Automation Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is Playwright used for?",
              options: ["Automation Testing", "Unit Testing", "Manual Testing"],
              correct: 0,
            },
            {
              question: "Which browser engines are supported by Playwright?",
              options: ["Chromium, WebKit, Firefox", "Chrome, Safari, Edge", "IE, Firefox, Opera"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "Debugging and Optimization",
        type: "video",
        duration: "00:30:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/playwright-video1.mp4",
          transcript: "Debugging and optimizing Playwright tests...",
        },
      },
      {
        id: 6,
        title: "Testing Best Practices",
        type: "video",
        duration: "00:55:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/playwright-video1.mp4",
          transcript: "Best practices for automated testing are essential for successful test automation projects...",
          resources: ["Testing Standards", "Automation Testing Principles"],
        },
      },
    ],
    5: [
      {
        id: 1,
        title: "Python Basics",
        type: "video",
        duration: "00:10:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/python-video1.mp4",
          transcript: "Introduction to Python programming...",
        },
      },
    ],
    6: [
      {
        id: 1,
        title: "Java Basics",
        type: "video",
        duration: "00:20:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/java-video1.mp4",
          transcript: "Introduction to Java programming...",
        },
      },
      {
        id: 2,
        title: "Java Syntax and Semantics",
        type: "reading",
        duration: "00:35:00",
        completed: false,
        content: {
          text: "Understanding Java syntax and semantics...",
          resources: ["Java Documentation", "Java Basics Guide"],
        },
      },
      {
        id: 3,
        title: "Java Control Flow",
        type: "reading",
        duration: "00:44:00",
        completed: false,
        content: {
          text: "Learn how to control program flow in Java...",
          resources: ["Java Loops", "Decision Making"],
        },
      },
      {
        id: 4,
        title: "Java Basics Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is Java?",
              options: ["Programming Language", "Coffee", "Tea"],
              correct: 0,
            },
            {
              question: "Which of the following is a Java keyword?",
              options: ["class", "method", "variable"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "Java Methods",
        type: "video",
        duration: "00:53:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/java-video1.mp4",
          transcript: "Methods in Java programming language...",
        },
      },
      {
        id: 6,
        title: "Java Classes and Objects",
        type: "reading",
        duration: "00:49:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/java-video1.mp4",
          transcript:
            "Classes and objects are fundamental concepts in object-oriented programming (OOP) languages like Java...",
        },
      },
      {
        id: 7,
        title: "Java Inheritance",
        type: "video",
        duration: "00:35:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/java-video1.mp4",
          transcript:
            "Inheritance is a key feature of object-oriented programming. Learn how to use it in Java programming language...",
        },
      },
      {
        id: 8,
        title: "Java Basics Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is Java?",
              options: ["Programming Language", "Coffee", "Tea"],
              correct: 0,
            },
            {
              question: "Which of the following is a Java keyword?",
              options: ["class", "method", "variable"],
              correct: 0,
            },
            {
              question: "What is a class in Java?",
              options: ["A method", "A blueprint for objects", "A variable"],
              correct: 1,
            },
            {
              question: "What is an object in Java?",
              options: ["An instance of a class", "A method", "A variable"],
              correct: 0,
            },
            {
              question: "What is inheritance in Java?",
              options: ["Reusing code", "Creating new classes", "Both of the above"],
              correct: 2,
            },
          ],
        },
      },
    ],
    7: [
      {
        id: 1,
        title: "Manual Testing Fundamentals",
        type: "video",
        duration: "00:10:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Introduction to manual testing...",
        },
      },
      {
        id: 2,
        title: "Testing Techniques",
        type: "video",
        duration: "00:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Learn manual testing techniques and strategies...",
          resources: ["Testing Guide", "Manual Testing Best Practices"],
        },
      },
      {
        id: 3,
        title: "Creating Test Cases",
        type: "video",
        duration: "00:20:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "How to create effective test cases...",
          resources: ["Test Case Examples", "Test Case Templates"],
        },
      },
      {
        id: 4,
        title: "Manual Testing Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is manual testing?",
              options: ["Testing by humans", "Automated testing", "Unit testing"],
              correct: 0,
            },
            {
              question: "What is a test case?",
              options: ["A set of conditions", "A test script", "A test plan"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "Reporting Defects",
        type: "video",
        duration: "00:25:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "How to report and track software defects...",
          resources: ["Defect Tracking Tools", "Defect Reporting Guidelines"],
        },
      },
      {
        id: 6,
        title: "Manual Testing Best Practices",
        type: "video",
        duration: "00:30:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Best practices for manual testing...",
          resources: ["Testing Standards", "Manual Testing Principles"],
        },
      },
      {
        id: 7,
        title: "Manual Testing Techniques",
        type: "video",
        duration: "00:35:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Effective manual testing techniques...",
          resources: ["Testing Strategies", "Manual Testing Patterns"],
        },
      },
      {
        id: 8,
        title: "Manual Testing Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What are the benefits of manual testing?",
              options: ["Human judgment", "Flexibility", "All of the above"],
              correct: 2,
            },
            {
              question: "What is a test case?",
              options: ["A set of conditions", "A test script", "A test plan"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 9,
        title: "Manual Testing Patterns",
        type: "video",
        duration: "00:40:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Effective manual testing techniques and patterns...",
          resources: ["Testing Strategies", "Manual Testing Patterns"],
        },
      },
      {
        id: 10,
        title: "Manual Testing Strategies",
        type: "video",
        duration: "00:45:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Effective manual testing techniques...",
          resources: ["Testing Strategies", "Manual Testing Patterns"],
        },
      },
      {
        id: 11,
        title: "Manual Testing Principles",
        type: "video",
        duration: "00:50:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/manual-testing-video1.mp4",
          transcript: "Effective manual testing techniques...",
          resources: ["Testing Strategies", "Manual Testing Patterns"],
        },
      },
    ],
    8: [
      {
        id: 1,
        title: "AI in Testing Fundamentals",
        type: "video",
        duration: "05:34:10",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Introduction to AI in testing...",
        },
      },
      {
        id: 2,
        title: "AI Testing Techniques",
        type: "video",
        duration: "06:45:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Learn AI testing techniques and strategies...",
          resources: ["Testing Guide", "AI Testing Best Practices"],
        },
      },
      {
        id: 3,
        title: "AI Testing Patterns",
        type: "video",
        duration: "07:30:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Effective AI testing techniques and patterns...",
          resources: ["Testing Strategies", "AI Testing Patterns"],
        },
      },
      {
        id: 4,
        title: "AI Testing Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is AI in testing?",
              options: ["Testing by machines", "Automated testing", "Manual testing"],
              correct: 0,
            },
            {
              question: "What is a test case?",
              options: ["A set of conditions", "A test script", "A test plan"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "AI Testing Strategies",
        type: "video",
        duration: "08:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Effective AI testing techniques...",
          resources: ["Testing Strategies", "AI Testing Patterns"],
        },
      },
      {
        id: 6,
        title: "AI Testing Best Practices",
        type: "video",
        duration: "09:00:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Best practices for AI testing...",
          resources: ["Testing Standards", "AI Testing Principles"],
        },
      },
      {
        id: 7,
        title: "AI Testing Techniques",
        type: "video",
        duration: "09:45:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/ai-testing-video1.mp4",
          transcript: "Effective AI testing techniques...",
          resources: ["Testing Strategies", "AI Testing Patterns"],
        },
      },
    ],
    9: [
      {
        id: 1,
        title: "Performance Testing Fundamentals",
        type: "video",
        duration: "03:34:22",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/performance-testing-video1.mp4",
          transcript: "Introduction to performance testing...",
        },
      },
      {
        id: 2,
        title: "Performance Testing Techniques",
        type: "video",
        duration: "02:45:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/performance-testing-video1.mp4",
          transcript: "Learn performance testing techniques and strategies...",
          resources: ["Testing Guide", "Performance Testing Best Practices"],
        },
      },
      {
        id: 3,
        title: "Performance Testing Patterns",
        type: "video",
        duration: "01:30:33",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/performance-testing-video1.mp4",
          transcript: "Effective performance testing techniques and patterns...",
          resources: ["Testing Strategies", "Performance Testing Patterns"],
        },
      },
      {
        id: 4,
        title: "Performance Testing Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is performance testing?",
              options: ["Testing by machines", "Automated testing", "Manual testing"],
              correct: 0,
            },
            {
              question: "What is a stress test?",
              options: [
                "Testing under normal conditions",
                "Testing under extreme conditions",
                "Testing under low load",
              ],
              correct: 1,
            },
            {
              question: "What is a load test?",
              options: [
                "Testing under normal conditions",
                "Testing under extreme conditions",
                "Testing under low load",
              ],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "Performance Testing Strategies",
        type: "video",
        duration: "02:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/performance-testing-video1.mp4",
          transcript: "Effective performance testing techniques...",
          resources: ["Testing Strategies", "Performance Testing Patterns"],
        },
      },
      {
        id: 6,
        title: "Performance Testing Best Practices",
        type: "video",
        duration: "01:42:11",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/performance-testing-video1.mp4",
          transcript: "Best practices for performance testing...",
          resources: ["Testing Standards", "Performance Testing Principles"],
        },
      },
    ],
    10: [
      {
        id: 1,
        title: "Security Testing Fundamentals",
        type: "video",
        duration: "03:34:22",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/security-testing-video1.mp4",
          transcript: "Introduction to security testing...",
        },
      },
      {
        id: 2,
        title: "Security Testing Techniques",
        type: "video",
        duration: "02:45:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/security-testing-video1.mp4",
          transcript: "Learn security testing techniques and strategies...",
          resources: ["Testing Guide", "Security Testing Best Practices"],
        },
      },
      {
        id: 3,
        title: "Security Testing Patterns",
        type: "video",
        duration: "01:30:33",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/security-testing-video1.mp4",
          transcript: "Effective security testing techniques and patterns...",
          resources: ["Testing Strategies", "Security Testing Patterns"],
        },
      },
      {
        id: 4,
        title: "Security Testing Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is security testing?",
              options: ["Testing by machines", "Automated testing", "Manual testing"],
              correct: 0,
            },
            {
              question: "What is vulnerability testing?",
              options: ["Testing for security vulnerabilities", "Performance testing", "Usability testing"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "Security Testing Strategies",
        type: "video",
        duration: "02:15:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/security-testing-video1.mp4",
          transcript: "Effective security testing techniques...",
          resources: ["Testing Strategies", "Security Testing Patterns"],
        },
      },
      {
        id: 6,
        title: "Security Testing Best Practices",
        type: "video",
        duration: "01:42:11",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/security-testing-video1.mp4",
          transcript: "Best practices for security testing...",
          resources: ["Testing Standards", "Security Testing Principles"],
        },
      },
    ],
    11: [
      {
        id: 1,
        title: "Introduction to API Testing",
        type: "video",
        duration: "03:34:22",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/api-testing-video1.mp4",
          transcript: "Introduction to API testing...",
        },
      },
      {
        id: 2,
        title: "API Testing Techniques",
        type: "video",
        duration: "02:45:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/api-testing-video1.mp4",
          transcript: "Learn API testing techniques and strategies...",
          resources: ["Testing Guide", "API Testing Best Practices"],
        },
      },
      {
        id: 3,
        title: "API Testing Patterns",
        type: "video",
        duration: "01:30:33",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/api-testing-video1.mp4",
          transcript: "Effective API testing techniques and patterns...",
          resources: ["Testing Strategies", "API Testing Patterns"],
        },
      },
      {
        id: 4,
        title: "API Testing Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is API testing?",
              options: ["Testing by machines", "Automated testing", "Manual testing"],
              correct: 0,
            },
            {
              question: "What is Postman?",
              options: ["API testing tool", "Database", "IDE"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "API Testing Strategies",
        type: "video",
        duration: "04:22:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/api-testing-video1.mp4",
          transcript: "Effective API testing techniques...",
          resources: ["Testing Strategies", "API Testing Patterns"],
        },
      },
      {
        id: 6,
        title: "API Testing Best Practices",
        type: "video",
        duration: "03:11:32",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/api-testing-video1.mp4",
          transcript: "Best practices for API testing...",
          resources: ["Testing Standards", "API Testing Principles"],
        },
      },
    ],
    12: [
      {
        id: 1,
        title: "Introduction to Mobile Testing",
        type: "video",
        duration: "00:34:22",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/mobile-testing-video1.mp4",
          transcript: "Introduction to mobile testing...",
        },
      },
      {
        id: 2,
        title: "Mobile Testing Techniques",
        type: "video",
        duration: "00:12:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/mobile-testing-video1.mp4",
          transcript: "Learn mobile testing techniques and strategies...",
          resources: ["Testing Guide", "Mobile Testing Best Practices"],
        },
      },
      {
        id: 3,
        title: "Mobile Testing Patterns",
        type: "video",
        duration: "00:30:33",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/mobile-testing-video1.mp4",
          transcript: "Effective mobile testing techniques and patterns...",
          resources: ["Testing Strategies", "Mobile Testing Patterns"],
        },
      },
      {
        id: 4,
        title: "Mobile Testing Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is mobile testing?",
              options: ["Testing by machines", "Automated testing", "Manual testing"],
              correct: 0,
            },
            {
              question: "What is Appium?",
              options: ["Mobile testing tool", "Database", "IDE"],
              correct: 0,
            },
          ],
        },
      },
      {
        id: 5,
        title: "Mobile Testing Strategies",
        type: "video",
        duration: "02:22:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/mobile-testing-video1.mp4",
          transcript: "Effective mobile testing techniques...",
          resources: ["Testing Strategies", "Mobile Testing Patterns"],
        },
      },
      {
        id: 6,
        title: "Mobile Testing Best Practices",
        type: "video",
        duration: "01:11:32",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/mobile-testing-video1.mp4",
          transcript: "Best practices for mobile testing...",
          resources: ["Testing Standards", "Mobile Testing Principles"],
        },
      },
    ],
    13: [
      {
        id: 1,
        title: "Introduction to API Testing",
        type: "video",
        duration: "00:34:22",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/web-development-video1.mp4",
          transcript: "Introduction to web development...",
        },
      },
      {
        id: 2,
        title: "API Testing Techniques",
        type: "video",
        duration: "00:12:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/web-development-video1.mp4",
          transcript: "Learn web development techniques and strategies...",
          resources: ["Development Guide", "Web Development Best Practices"],
        },
      },
      {
        id: 3,
        title: "API Testing Patterns",
        type: "video",
        duration: "00:30:33",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/web-development-video1.mp4",
          transcript: "Effective web development techniques and patterns...",
          resources: ["Development Strategies", "Web Development Patterns"],
        },
      },
      {
        id: 4,
        title: "API Testing Fundamentals Quiz",
        type: "quiz",
        completed: false,
        content: {
          questions: [
            {
              question: "What is Front-end development?",
              options: [
                "Development of the user interface",
                "Development of the server-side logic",
                "Development of the database",
              ],
              correct: 0,
            },
            {
              question: "What is HTML?",
              options: ["Web development tool", "Markup language", "IDE"],
              correct: 1,
            },
          ],
        },
      },
      {
        id: 5,
        title: "API Testing Strategies",
        type: "video",
        duration: "02:22:00",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/web-development-video1.mp4",
          transcript: "Effective web development techniques...",
          resources: ["Development Strategies", "Web Development Patterns"],
        },
      },
      {
        id: 6,
        title: "API Testing Best Practices",
        type: "video",
        duration: "01:11:32",
        completed: false,
        content: {
          videoUrl: "https://test.test.test/web-development-video1.mp4",
          transcript: "Best practices for web development...",
          resources: ["Development Standards", "Web Development Principles"],
        },
      },
    ],
  },

  // Quiz attempts tracking
  quizAttempts: [
    {
      id: 1,
      userId: 1,
      courseId: 1,
      lessonId: 3,
      attemptDate: "2023-06-17T09:45:00Z",
      score: 90,
      passed: true,
      answers: [0, 0], // User's selected answers
    },
  ],

  userStats: [
    {
      userId: 1,
      coursesInProgress: 1,
      completedCourses: 1,
      totalHours: 28,
      totalCertificates: 1,
      lastUpdated: "2023-07-25T12:00:00Z",
    },
  ],

  failedLoginAttempts: {
    // Structure: { email: { count: number, lastAttempt: string } }
  },

  userRatings: [
    {
      userId: 3,
      courseId: 5,
      rating: 5,
      comment: "Excellent cybersecurity course! The labs were incredibly helpful.",
      createdAt: "2024-02-20T12:10:15Z",
    },
    {
      userId: 4,
      courseId: 8,
      rating: 4,
      comment: "Great blockchain development course. Complex concepts explained well.",
      createdAt: "2024-02-22T09:20:18Z",
    },
    {
      userId: 5,
      courseId: 6,
      rating: 5,
      comment: "Comprehensive data science course. Loved the practical assignments!",
      createdAt: "2024-02-21T14:45:12Z",
    },
    {
      userId: 6,
      courseId: 7,
      rating: 4,
      comment: "Solid React Native course. Good balance of theory and practice.",
      createdAt: "2024-02-23T15:25:40Z",
    },
    {
      userId: 7,
      courseId: 9,
      rating: 3,
      comment: "Good UI/UX basics but could use more advanced topics.",
      createdAt: "2024-02-20T13:40:55Z",
    },
    {
      userId: 11,
      courseId: 12,
      rating: 5,
      comment: "Mobile testing concepts were explained perfectly!",
      createdAt: "2024-02-22T16:15:00Z",
    },
    {
      userId: 12,
      courseId: 14,
      rating: 4,
      comment: "Very informative course on modern testing practices.",
      createdAt: "2024-02-23T10:05:30Z",
    },
    {
      userId: 13,
      courseId: 11,
      rating: 5,
      comment: "Amazing API testing course. Very thorough coverage.",
      createdAt: "2024-02-24T11:30:45Z",
    },
    {
      userId: 14,
      courseId: 13,
      rating: 4,
      comment: "Web development fundamentals covered comprehensively.",
      createdAt: "2024-02-23T17:30:22Z",
    },
    {
      userId: 3,
      courseId: 14,
      rating: 4,
      comment: "Great introduction to testing methodologies.",
      createdAt: "2024-02-24T08:22:33Z",
    },
  ],

  // Add funds transaction history
  fundsHistory: [
    {
      userId: 1,
      amount: 50.0,
      type: "credit",
      timestamp: "2023-11-01T10:30:00Z",
      description: "Account top up",
    },
    {
      userId: 1,
      amount: 49.99,
      type: "debit",
      timestamp: "2023-11-02T14:20:00Z",
      description: "Course enrollment: Introduction to Web Development",
    },
    {
      userId: 1,
      amount: 100.0,
      type: "credit",
      timestamp: "2023-11-03T09:45:00Z",
      description: "Account top up",
    },
    {
      userId: 1,
      amount: 79.99,
      type: "debit",
      timestamp: "2023-11-04T16:30:00Z",
      description: "Course enrollment: Advanced JavaScript Programming",
    },
    {
      userId: 1,
      amount: 100.0,
      type: "credit",
      timestamp: "2024-12-03T09:45:00Z",
      description: "Account top up",
    },
  ],
};

module.exports = mockData;
